### ISSUE TITLE
Feedback Tuning

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-lsp#108]
All the "foo is defined" messages should not be displayed by default, that is too noisy; turn it into a server option.

**Comment by Alizter** [comment]
Will this require some message refactoring upstream

**Comment by ejgallego** [comment]
Hopefully not, I think we can just drop (or better make an option) `Info` level messages and still have thing working fine.

This issue is really a reminder.

Note that Maxime fixed a lot of cases where `Info` vs `Notice` was used incorrectly in https://github.com/coq/coq/pull/10612

**Comment by Alizter** [comment]
@ejgallego In that case, that seems fine.

**Comment by ejgallego** [comment]
I think so but indeed lots of fine tuning likely to be done here.
