### ISSUE TITLE
Goal window should update on cursor movement rather than mouse click

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#132]
Today we are updating the goal window when the mouse is clicked. We should rather do this when the cursor changes position so that movement with the arrow keys also updates the goals window.

**Comment by ejgallego** [comment]
I guess you mean by default? The `show_goals_on` function already allows to show goals on cursor movement.

I think not having that by default makes most sense, but indeed we lack the way to test this kind of UI hypothesis.

Given that goal printing is quite expensive, I'd suggest we leave the default as only on click for now, what do you think?

**Comment by ejgallego** [comment]
[Moreover quite a few users have expressed their preference for a goal pin functionality, which suggest that click only may be a good default]

**Comment by Alizter** [comment]
I was not aware we had the option to change it when I created this issue so I think it can be closed.

**Comment by ejgallego** [comment]
Still whether to do this by default is open IMHO, also I'm sure the documentation can be improved too.

Maybe a configuration assistant would be useful here, so the first time the user runs the extension, what options to use are asked.
