### ISSUE TITLE
Display warnings in error browser

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#195]
We should display warnings in the error browser, or at least make a new tab for them.

**Comment by ejgallego** [comment]
Indeed I was thinking about this when I introduced the error browser, I'm a bit unsure tho about the HCI story here.

For errors, you clearly want to have a dedicated display as it requires action; however, what's the story for warnings? Should these just be addressed by a code action instead?

**Comment by Alizter** [comment]
@ejgallego I was thinking about this again and I noticed something that I didn't make clear before. We don't want the warnings to display all the time, only when we have the cursor over them just like with errors. Having the warnings also display in the error browser (even under a dedicated warnings tab that you can ignore) would be ideal.

**Comment by Alizter** [comment]
At the moment the only way to view the warnings is to hover your mouse over them, and it makes it difficult to read sometimes.

**Comment by ejgallego** [comment]
I see what you mean, still not sure about the UI design for this, warnings are already displayed in the diagnostics window, and a code action should happen for the warning (ignore / fix)

There is a key difference between warnings and errors: Errors contain complex content, like unification failures, etc...

However, warnings are often a single text line, so what is the advantage about having a decidated display over the already standard display? It seems to me that the current display in the list works fine, but I see your point about the workflow with the panel.

**Comment by ejgallego** [comment]
I think this could be a good topic to discuss in the next meeting, is it OK if we use the tag to mark such topics?

**Comment by Alizter** [comment]
Having a goal panel, a proof script and a diagnostic panel open is not feasible for people with tiny laptops.

**Comment by ejgallego** [comment]
Actually could the diagnostic window maybe docked in a different way?

I think we can come with the good UI panel for warnings, but these being actionable, IMHO we need to chat a bit about the design, happy to take a PR tho with a preliminary design.

The current error browser has some problems actually too.

**Comment by Alizter** [comment]
I was thinking something like a "warnings browser" under the error browser which can be closed by default.

**Comment by ejgallego** [comment]
The thing is that if you see a warning, you wanna go to hover and click "fix" right away, don't you?

We could duplicate this in the info panel, but certainly low prio IMHO.

**Comment by ejgallego** [comment]
I think that #308 plus this is enough as to try something sooner.
