### ISSUE TITLE
Goal not updating after `intros`

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#197]
Here is an example of the goal not updating after an `intros` statement together with some unicode characters.

```coq
Axiom P : nat -> Prop.
Axiom foo : forall {n}, P (S n) -> P n.
Ltac foo := apply foo.
Infix "⊆" := lt (at level 10).

Goal forall Γ Δ, Γ ⊆ Δ -> P Γ.
intros Γ Δ s.
foo.
```
Cursor is first before the `intros`.
![image](https://user-images.githubusercontent.com/8614547/213451959-7297e339-3087-4530-b14d-a34306443d6a.png)

Cursor is after the terminating `.` and the goal has not updated.
![image](https://user-images.githubusercontent.com/8614547/213451986-f73f8fe7-1896-48a3-8935-4f798ebf250e.png)

Next line the goal updates.
![image](https://user-images.githubusercontent.com/8614547/213452013-69aea53e-d30f-4099-af96-197746c55738.png)

Notice the correct behaviour when the cursor is after the terminating `.` for `foo`.
![image](https://user-images.githubusercontent.com/8614547/213452040-49f8ef79-8db0-4314-92de-d4a70ec82a5e.png)

**Comment by ejgallego** [comment]
That's the same than #193, thanks. The server is not translating Coq locations to LSP locations properly.

In particular, once we store `Range.`t  (properly converted) in `Fleche.Doc.t`, then things will work fine automatically.
