### ISSUE TITLE
Restarting LSP does not kill coq-lsp process

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#230]
After having restarted LSP several times, I noticed that the old processes were not being killed.

**Comment by ejgallego** [comment]
I've seen this only once, but likely my computer is too fast to reproduce a race here. There could be 2 reasons:
- Node / `vscode-languageclient` problem: in this case the issue should be forward upstream detailing that the `stop()` method has this problem, c.f. https://github.com/microsoft/vscode-languageserver-node
- The extension was disposed and indeed we didn't push the `client` to the extension `subscriptions`, this seems like a bug! Can we check what the reference extensions do here? But for sure something to try to see if that fixes your problem.

How often does this problem happen?

**Comment by ejgallego** [comment]
Indeed, @artagnon found that the exit procedure was totally broken, PR incoming, I bet that helps with this problem.
