### ISSUE TITLE
Search gives output in one long line (difficult to read)

### ISSUE THREAD

**Issue by orilahav** [ejgallego/coq-lsp#282]
Here is a screenshot:

<img width="1206" alt="Screen Shot 2023-02-05 at 16 33 10" src="https://user-images.githubusercontent.com/14070781/216825661-f1b17239-cf4a-4137-a459-29d4f9f2952f.png">

**Comment by Alizter** [comment]
This was fixed in main. Here is how it looks:
![image](https://user-images.githubusercontent.com/8614547/216831880-a7a6eff7-7143-46dd-87bb-e041c4344430.png)

**Comment by ejgallego** [comment]
Indeed sorry @orilahav , this is a bug in in 0.1.4, we will release a fixed version ASAP; also our UI for Search is far from even usable, I hope we can improve it soon.

**Comment by ejgallego** [comment]
Note this was solved by #272
