### ISSUE TITLE
[server] Initialize request doesn't handle properly the case where `workspaceFolders` is `null`.

### ISSUE THREAD

**Issue by orilahav** [ejgallego/coq-lsp#283]
- open a new file in VSCode (via its menu - file:new).
- name the file something.v
- coq-Isp doesn't check the file ("no goals")

It does check the file if I save it and reopen it from the menu.

**Comment by Alizter** [comment]
I am not able to reproduce on main.

**Comment by ejgallego** [comment]
Indeed @orilahav I can't reproduce this, maybe it is an instance of the problem that #287 solves?

**Comment by ejgallego** [comment]
Hi @orilahav , any news on this?

**Comment by orilahav** [comment]
Now it fails to start (attached trace).
Perhaps something is broken with my installation if it works for others.
[coq_lsp.txt](https://github.com/ejgallego/coq-lsp/files/10895807/coq_lsp.txt)

**Comment by ejgallego** [comment]
Mmm, that's indeed strange, what version of the extension do you have installed?

Thanks a lot for the log, could you try setting the `Coq LSP > Trace` setting to verbose?

It could be that for some reasons the settings got corrupted, could you try with a new VS Code profile too?

[A way to do this is to rename / remove .vscode files such as `~/.vscode` and the one in the project.

I am improving the error message for the next release by the way, so we could better debug these cases, also we will add platform information.

**Comment by ejgallego** [comment]
In particular this piece of code:
```
let client_version = context.extension.packageJSON.version;
    const initializationOptions = CoqLspServerConfig.create(
      client_version,
      wsConfig
    );
```

**Comment by ejgallego** [comment]
So actions here:
- Improve error message
- Make init more resilient (show on default)
- Print platform

**Comment by orilahav** [comment]
I'm using version 0.1.6.
verbose log: 
[Coq_lsp_verbose.txt](https://github.com/ejgallego/coq-lsp/files/10900304/Coq_lsp_verbose.txt)

**Comment by ejgallego** [comment]
Hi @orilahav , oh indeed that's a bug in coq-lsp!!

```json
    "workspaceFolders": null
```

I really need to read the spec more carefully...

Fix to main incoming.

**Comment by ejgallego** [comment]
While we prepare the fixed release, you should be able to workaround this by using "Open Folder" option in vscode.

Thanks and sorry for all the trouble.
