### ISSUE TITLE
Auto admit goal selectors

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#300]
It would be nice if we could have more fine grained auto admits.

For example the following proof is incomplete:

```coq
Goal nat * nat * nat.
Proof.
  refine (_,_,_).
  - apply S.
  - apply S.
    exact 1.
  - exact 1.
Qed.
```
A use might want to work on the middle branch but the first branch prevents this from happening. coq-lsp should detect these situations and automatically insert an `admit.` so that the goal selector is properly closed. Something similar already happens in Coq by default when you do `{ incompelte. }`, using the bracket selectors.

**Comment by ejgallego** [comment]
I was convinced I had opened an issue for this already, but it seems I had not (#33 is a bit close tho)

This is def in the radar, it is a bit tricky tho due different kinds of bullet modes, for example in math-comp there are not "strict".

A related issue is when a user closes the goal, ask them to insert `by / now`, that makes for a very nice error recovery as we can know when the goal is supposed to be closed.

**Comment by Alizter** [comment]
> This is def in the radar, it is a bit tricky tho due different kinds of bullet modes, for example in math-comp there are not "strict".

Yes, we can query the bullet mode however.

> A related issue is when a user closes the goal, ask them to insert `by / now`, that makes for a very nice error recovery as we can know when the goal is supposed to be closed.

I would like to see more support upstream for finishing tactics so that we can detect them nicely. We could even have an attribute for by / now like `#[finisher]` or something so that we can detect such a case nicely.

**Comment by ejgallego** [comment]
I think the Coq terminology is `solve`. I'm happy using something simpler.

Bullet mode is quite messy tho, but I guess after we merge some improvemens to error recovery in #262 , the bullet case can be plugged into the module infra.

Hard to develop this without a test-suite tho.

**Comment by ejgallego** [comment]
cc #29
