### ISSUE TITLE
Missing document symbol names

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#323]
![image](https://user-images.githubusercontent.com/8614547/218888082-75760158-7caa-48c6-9443-e660617b1154.png)

We are missing document symbol names for:
- Record and Class fields (Field)
- Constructors (Constructor)
- Fixpoints (Fixpoint)
- Instances (Instance)

**Comment by ejgallego** [comment]
Actually that's the `detail` field in the protocol, I was thinking of adding there the type?

But sure, we can add that style of decoration too :+1:
