### ISSUE TITLE
Error message browser becomes non-visible when there are many goals.

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-lsp#441]
Reported by Tomás Díaz

**Comment by Alizter** [comment]
Does it not have a scroll bar?

**Comment by ejgallego** [comment]
Yes but the user needs to scroll to see the error.

**Comment by Alizter** [comment]
OK, then in this case it is not really bug but a quality of life improvement. As we discussed before, we should have a divider.

**Comment by ejgallego** [comment]
This was fixed by #455 IMO
