### ISSUE TITLE
feature request: Hover should show implicit arguments

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#448]
When hovering over a term, all the arguments are currently printed. We should make it so that implicit arguments are printed with `{ }` so that they can easily be ignored by the user. I believe not printing them at all is also an option, but may be confusing.

**Comment by ejgallego** [comment]
Yes!

Also when hovering on an application we should display the implicits there, however that requires some UI design before implementation.

**Comment by ejgallego** [comment]
@Alizter is there a command in Coq that wll print types like this?

**Comment by Alizter** [comment]
`About` has information about implicit arguments.
