### ISSUE TITLE
[meta] Standalone compiler

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-lsp#472]
This issue is to track coq-lsp standalone compiler.

### Why a standalone compiler:

coq-lsp was designed as an instrumentalization of a simple, functional compiler with effects and memoization, and can already check and save files.

Given coq-lsp features, it makes sense to provide an interface similar to coqc. In particular this can allow checking files more efficiently, and greater incremental capabilities. It can also enable easy compilation of theories that are partially broken.

### Preliminary todo

1. the hardest todo is to pick a name for the compiler, `scoq`, `icoq` ?
2. simple file compilation
3. simple compilation of file + deps
4. improve 3 to use in-memory marshall cache
5. extend 3 to full project compilation

**Comment by Alizter** [comment]
Some name suggestions:
- `hatch`
- `pollo`
- `sencillo`
- `squawk`
- `gallito`

**Comment by ejgallego** [comment]
I used `fcc` but IMHO the name issue is still open, as I think we can do better :)
