### ISSUE TITLE
Expose Section Variable Determining API in coq-lsp

### ISSUE THREAD

**Issue by HazardousPeach** [ejgallego/coq-lsp#495]
The ML API has a mechanism to determine which section variables were used by a proof. Ideally, coq-lsp would also allow this.

Emilio's comment on Zulip here:
https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Determining.20section.20variables.20used/near/365974818

**Comment by ejgallego** [comment]
Discussion on https://github.com/ejgallego/coq-serapi/issues/339

**Comment by ejgallego** [comment]
Implemented in https://github.com/ejgallego/coq-serapi/pull/342 , will port to coq-lsp once we validate the SerAPI change.

**Comment by ejgallego** [comment]
Closed upstream, happy to resurrect it if there is a need.
