### ISSUE TITLE
Nix (macOS-latest) CI job is broken

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-lsp#501]
cc @Alizter

**Comment by Alizter** [comment]
Part of a bigger issue:

https://github.com/cachix/install-nix-action/issues/183

**Comment by ejgallego** [comment]
Thanks for the investigation, I've temporarily disabled it (no point in getting red for all PRs), hopefully the problem is fixed soon.

**Comment by ejgallego** [comment]
Not fixed by #502
