### ISSUE TITLE
Fixed light color in the goal panel

### ISSUE THREAD

**Issue by ineol** [ejgallego/coq-lsp#532]
**Describe the bug**

The color of variables in the goal panel is fixed to light blue, which is difficult to read with light color themes.

**Expected behavior**
The syntax highlighting in the goal panel should follow that of the editor theme.

**Screenshots**
![image](https://github.com/ejgallego/coq-lsp/assets/37965/cf23d608-3793-4b19-9770-c46cfd41cce6)

**Desktop (please complete the following information):**
 - Operating system linux
 - coq-lsp version 0.1.7
 - VS Code version 1.80.1

**Comment by Alizter** [comment]
That's a good point. I believe we only tested this with a dark background hence why we didn't notice. We use react and I think a cutstom style sheet to colour the syntax in this window. It definitely would be an improvement to use the editor highlighting. PRs are welcome!

**Comment by ejgallego** [comment]
Thanks a lot for the report @ineol , indeed we should ship better styles for the different VsCode styles, hope to fix ASAP.

Let us know if you have any suggestions, or if you would like to contribute a particular style sheet.

You can open the CSS / HTML developer tools in VSCode normally and try a fix.

**Comment by bhaktishh** [comment]
I was looking into this, and I'm not sure syncing with the current theme is as desirable as just setting a fixed color for `light` and`dark` themes. With respect to gathering information from the current theme, there's no way of knowing how many colors are distinct, and it might result in a situation where two distinct symbols get the same color. [Also, as far as I can tell, the solution for accessing current theme color information is [hacky at best](https://github.com/microsoft/vscode/issues/32813#issuecomment-798680103) with seemingly no hopes of being added to the API.] I tried out the much simpler solution of setting just two different values for `light` and `dark` themes [here](https://github.com/bhaktishh/coq-lsp-bhaktishh/commit/b23d5dcc528fd3837cf78161116996ca92764c25) and it worked quite well, I'm just a bit conflicted on the color choices -- i arbitrarily changed the ones that looked "too light" to work with a light background, and just let the rest be.

**Comment by bhaktishh** [comment]
@ineol @ejgallego @Alizter any thoughts?

**Comment by ineol** [comment]
@bhaktishh I looks much more readable! I would be content if it were merged as far as I am concerned.

**Comment by Alizter** [comment]
I'm content with those colour choices, although I never use light themes in practice. As long as users are able to customise the colours via their theme, I think we are free to choose whatever we deem acceptable.

**Comment by ejgallego** [comment]
Hi @bhaktishh , thanks for the detailed analysis and PR, IMHO it is a much needed improvement.

But as we get more users we should get more familiar with themes.

Something to remark here is that coq-lsp view is now used by jsCoq "2.0" , and I think @corwin-of-amber has made some changes to style too.

How to best coordinate the shared use of the view is kinda open, for example Lean puts their view in the extension repos  https://github.com/leanprover/vscode-lean4 (`infoview`) dir, then this package is used for their web setup.

Maybe we could discuss about it in a meeting.
