### ISSUE TITLE
Latest coq-lsp crashes when using a Ltac2 notation

### ISSUE THREAD

**Issue by quarkcool** [ejgallego/coq-lsp#533]
**Describe the bug**
With the main branch, and vendored Coq / Coq stdlib, coq-lsp crashes repeatedly when importing module Ltac2.Notations and using a Ltac2 notation (such as refine) within a Ltac2 definition.

Following message appears in VSCode: 
"The Coq LSP Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information."

**To Reproduce**
1. Create a file in VSCode with the following contents:

```
Require Export Ltac2.Notations.

Ltac2 test () := refine '(id _).
```

2. See coq-lsp crash 5 times

**Expected behavior**
It should handle Ltac2 notations.

**Desktop (please complete the following information):**
 - Operating system: OS X
 - coq-lsp version: c23ddf4d0f1e7d0facd38cf044215856046de391 
 - VS Code version: 1.80.1

**Comment by ejgallego** [comment]
Thank you very much, will be fixed by https://github.com/ejgallego/coq-serapi/pull/349

**Comment by quarkcool** [comment]
Amazing thank you, latest commit is working

**Comment by ejgallego** [comment]
Glad to hear! This was not a problem in coq-lsp itself but in serlib, which has to do unfortunately some unsafe tricks :(
