### ISSUE TITLE
[vscode client] Export an API for ViZX integration

### ISSUE THREAD

**Issue by bhaktishh** [ejgallego/coq-lsp#538]
As documented [here](https://code.visualstudio.com/api/references/vscode-api#extensions), it's possible for extensions to export an API for other extensions to use. I want to add an API for `coq-lsp` but I'm not sure what functions would make sense to include in the API. Are there thoughts on the same?

**Comment by Alizter** [comment]
Let's start with some use cases? What kinds of extensions using the internals of this extension do you have in mind?

**Comment by bhaktishh** [comment]
For example, currently [ViZX](https://github.com/inQWIRE/ViZX) is hardwired into the coq-lsp code, which works for one extension but probably isn't scaleable or good practice if anyone wants to add more (which there seems to be interest in). Any kind of domain specific tool for Coq that doesn't necessarily make sense being integrated into the larger coq-lsp ecosystem because it's not general purpose enough, would probably want to interact with Coq, and sending requests to and from the server seems like a natural part of developing something like this. Something I'm working on currently needs to make a `proof/goals` request for several states, something that isn't possible outside of coq-lsp. However, exporting a function that lets you make the request at a particular document position would make this possible. Things that don't necessarily make sense as commands, but would only be used by another application. Getting goals is one, but any of the custom LSP commands seem like things that could be used, and this seems easy enough to implement.

**Comment by Alizter** [comment]
Are we talking about the coq-lsp server itself? Or specifically the VS Code extension? I understood the latter, but the former is completely agnostic to the client.

**Comment by bhaktishh** [comment]
I guess my idea is to make it easier to interact with the server too, via an extension API, instead of having to set up everything again with the server.

**Comment by ejgallego** [comment]
Hi @bhaktishh , I think that what you propose makes total sense, I'll be happy to start experimenting with extension API.

I think the only constraint I can see for now is that the extension hooks should be "pure" or "functional" as to work better with the server.

For example I think the first API we could add is an API that allows the extension to insert a new collapsible tab for the goal view, and passing the context / goals info for that.

**Comment by ejgallego** [comment]
I've taken the freedom to rename this issue to be about supporting `ViZX` and the extension that is needed. I'll open other issue for different desired API integrations.
