### ISSUE TITLE
Progress report bar

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#54]
Some sort of progress bar report, or status indicating checked build. We need to investigate what support in LSP there already is for this.

**Comment by ejgallego** [comment]
Lean does this in vscode, we can have a look to see how they did implement it.

**Comment by ejgallego** [comment]
An easy thing to try is to have do_check implement https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverInitiatedProgress
