### ISSUE TITLE
Multiple warning display options in _CoqProject are not handled correctly

### ISSUE THREAD

**Issue by mituharu** [ejgallego/coq-lsp#540]
**Describe the bug**
If multiple warning display options are specified in the _CoqProject file, they are not respected.

**To Reproduce**
1. Specify multiple warning display options in the _CoqProject file.  For example,
```
-arg -w -arg -notation-overridden
-arg -w -arg +duplicate-clear
-arg -w -arg +non-primitive-record
-arg -w -arg +undeclared-scope
-arg -w -arg +deprecated-hint-without-locality
```
2. Open some .v file in the directory.
3. Type `Print Options.` and move the cursor to just before the period.

**Expected behavior**
The output contains the line `Warnings: "-notation-overridden,+duplicate-clear,+non-primitive-record,+undeclared-scope,+deprecated-hint-without-locality"` with a comma-separated string.

**Actual behavior**
The corresponding line has no comma: `Warnings: "-notation-overridden+duplicate-clear+non-primitive-record+undeclared-scope+deprecated-hint-without-locality"`

**Desktop (please complete the following information):**
 - Operating system: macOS Ventura
 - coq-lsp version: v0.1.7
 - VS Code version: 1.81.1

**Comment by ejgallego** [comment]
Hi @mituharu , indeed that was a silly bug, Coq's warnings API is a bit confusing for me.

Will be fixed very soon, thanks a lot for the very careful bug report.

**Comment by ejgallego** [comment]
I'd be nice to add this to the test suite.
