### ISSUE TITLE
Updating Nix documenation

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#552]
@ejgallego Let's continue the discussion about updating the documentation about nix here.

**Comment by Alizter** [comment]
Ok so I see the documenation you were asking about:

https://github.com/ejgallego/coq-lsp/blob/main/README.md#-server

We should not be listing a PR here but rather mention that it is available via nixpkgs as `coqPackages.coq-lsp`. An example of a flake that uses it in a dev environment is the Nix flake in the HoTT repo:

https://github.com/HoTT/Coq-HoTT/blob/master/flake.nix

**Comment by Alizter** [comment]
@ejgallego Do you mean upsating the 8.17/8.18 releases in nixpkgs?

**Comment by ejgallego** [comment]
@Alizter I was thinking of something more specific to coq-lsp, in the following way:

- coq in nixPackages is the standard release
- however when users select the `coq-lsp` derivation, we use the `coq` derivation but with the sources pinned at the `+lsp` branches.

The upstream stragegy in Coq should be to release the 8.17.2 and 8.18.1 packages with these fixes as they are critical, but that seems pretty complex.

`opam` users have a pretty easy solution with `opam pin`

**Comment by ejgallego** [comment]
The bug we have to workaround now is that quite a few tactics and parsing fucntions do actually swallow the async exceptions , this is a PITA for users, as then what happens is that `coq-lsp` thinks the tactic did fail, instead of being interrupted.

**Comment by ejgallego** [comment]
This bug makes advanced math-comp development for example unusable.

**Comment by ejgallego** [comment]
@Alizter how's the current status of the docs for the VSCode extension?

**Comment by Alizter** [comment]
The instructions for the extension are for the dev version. There are two ways to install the extension on Nix:
- You can configure the extension via a derivation; like any other vscode extension setup. Nothing special here.
- You can install the extension straight from vscode (this is infact what I do).

**Comment by ejgallego** [comment]
Thanks. IIUC this means we can just move the Nix instructions to `CONTRIBUTING > Building from source` ?

**Comment by Alizter** [comment]
Well not everybody who wants to build from source necessarily is a contributor. ;-)

**Comment by ejgallego** [comment]
Indeed it is not, however these cases seem too rare to put them into the contributing guide.

Would you like a new `docs/build.md` document?

**Comment by ejgallego** [comment]
:+1:  

I think I will stop with the README for now, as I've updated the install instructions to more recent developments (windows will require a few tweaks, but the "official" installers are finally ready)

I guess the next step for the readme would be to have 2 minutes demo video at the start.

I'd try to reorg the contributing guide / roadmap etc... a bit, in particular to guide each type of user to their relevant info.
