### ISSUE TITLE
edit needed to start client after a restart

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#563]
Whilst editing a document do a restart. You will see that the webview is not immediately updated. You need to edit the document and cause a change for it to wake up.

Ideally after a restart you wouldn't have to do this.

**Comment by ejgallego** [comment]
Would be great if we could add a test-case for this.

**Comment by ejgallego** [comment]
I wonder what we can do, this seems to be in charge by the `vscode-languageserver` library, when we start it doesn't re-update the document. Let's update the version, there are many bugfixes.

**Comment by Alizter** [comment]
Note that I don't have this problem with ocaml-lsp or rust-analyzer.

**Comment by ejgallego** [comment]
Yes, this was due to a long needed scheduling queue, lazy on my part, now fixed in #566
