### ISSUE TITLE
Formatting of terms missing in error messages

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#571]
**Describe the bug**
The terms that appear in error messages have some formatting to them. This seems to disappear when displaying errors unlike the display in the goals panel.

![image](https://github.com/ejgallego/coq-lsp/assets/8614547/56342f52-8147-4212-93eb-e5ff27cad614)

**Expected behavior**

CoqIDE and ProofGeneral both have formatted error messages (since Coq outputs them).

**Comment by ejgallego** [comment]
Thanks for the report, likely some CSS / HTML problem preventing the breaking algo from working properly.

We need to get some time to rework that, it should be possible tho to find a quick workaround for this particular problem.

**Comment by ejgallego** [comment]
@Alizter would be helpful if we could add a file with this problem to the `examples` folder, to be eventually turned into a test.

**Comment by ejgallego** [comment]
One part of this bug should be fixed by #586, however I think still we may be missing the scroll bar here, please open a new bug with an example if things don't overflow properly.
