### ISSUE TITLE
Minor issue with vim and cursor tracking

### ISSUE THREAD

**Issue by qcfu-bu** [ejgallego/coq-lsp#614]
I have a minor issue when it comes to using coq-lsp together VscodeVim.

In vim normal-mode, when the cursor is placed on the period at the end of a tactic, the Goals do not update to reflect the application of the tactic.
```
rewrite H1.
          ^
```

Only when the cursor is moved after the period does the goal update.
```
rewrite H1.
           ^
```

This behavior is a little annoying when browsing through source files in normal-mode as the tactics at the end of each line do not get applied until the start of the next line.

When trying this with Lean4's extension, they seem to register cursor's position across the entire tactic.

```
rewrite H1.
^^^^^^^^^^^
```

**Comment by qcfu-bu** [comment]
Nvm, turning on 'Goal_after_tactic' gives me the exact functionality I wanted.

**Comment by Alizter** [comment]
@ejgallego how do you feel about making this setting the default?

**Comment by ejgallego** [comment]
Happy to do so! Indeed seems like the most reasonable default. 

Note that in `main` the `proof/goals` request does indeed take the parameter, so different goals requests can use a different setting; this is IMHO better, as it allows the client to be more flexible.

This setting is a bit weird in the sense that for example, it doesn't affect errors or messages, that we currently relay on the `proof/goals` call.

**Comment by ejgallego** [comment]
@qcfu-bu sorry for the trouble, indeed I think we should change the default of this option.

**Comment by qcfu-bu** [comment]
> @qcfu-bu sorry for the trouble, indeed I think we should change the default of this option.

No worries! The experience after turning it on so much more enjoyable!

**Comment by Alizter** [comment]
We also all have it turned on which is why it probably makes sense to be the default now. :)
