### ISSUE TITLE
Erroneous Coq files with incorrect AST ranges for valid steps

### ISSUE THREAD

**Issue by pcarrott** [ejgallego/coq-lsp#633]
**Describe the bug**
For files with errors, coq-lsp does not always return the correct ranges in the AST of valid steps.

**To Reproduce**
1. Make sure to have only Coq and coq-lsp installed in your Coq environment (e.g. no Iris or stdpp). 
2. Download [this file](https://github.com/DKXXXL/dimsum-learning/blob/66bc038471a81b73654c9db0e30ca22f8fbd3112/dimsum/base.v).
3. Install [CoqPyt](https://github.com/sr-lab/coqpyt) and run in the same directory as the downloaded file:
```python
import os
from coqpyt.coq.base_file import CoqFile

with CoqFile(os.path.join(os.getcwd(), "base.v")) as cf:
    step = cf.steps[64]
    print("Text:", repr(step.short_text))
    print("Full:", repr(step.text))
    print("Span:", repr(step.ast.span))
    print("Range:", repr(step.ast.range))

    step = cf.steps[65]
    print("\nText:", repr(step.short_text))
    print("Full:", repr(step.text))
    print("Span:", repr(step.ast.span))
    print("Range:", repr(step.ast.range))
```
4. The output should be:
```python
Text: ''
Full: ') :=\n  map_imap (λ l v, Some (default v (m1 !! l))) m2.\n'
Span: {'v': {'control': [], 'attrs': [], 'expr': ['VernacSynterp', ['VernacBeginSection', {'v': ['Id', 'theorems'], 'loc': {'fname': ['InFile', {'dirpath': None, 'file': '/home/pcarrott/Documents/Repos/test/base.v'}], 'line_nb': 276, 'bol_pos': 10855, 'line_nb_last': 276, 'bol_pos_last': 10855, 'bp': 10863, 'ep': 10871}}]]}, 'loc': {'fname': ['InFile', {'dirpath': None, 'file': '/home/pcarrott/Documents/Repos/test/base.v'}], 'line_nb': 276, 'bol_pos': 10855, 'line_nb_last': 276, 'bol_pos_last': 10855, 'bp': 10855, 'ep': 10872}}
Range: {'start': "{'line': 275, 'character': 0, 'offset': 10855}", 'end': "{'line': 275, 'character': 0, 'offset': 10872}"}

Text: 'Section theorems. Lemma map_union_weak_insert {K A} `{Countable K} (m1 m2 : gmap K A) (i : K) (x'
Full: '\nSection theorems.\n  Lemma map_union_weak_insert {K A} `{Countable K} (m1 m2 : gmap K A) (i : K) (x'
Span: None
Range: {'start': "{'line': 275, 'character': 0, 'offset': 10872}", 'end': "{'line': 277, 'character': 80, 'offset': 11040}"}
```
The span and the range are obtained directly from the AST returned by coq-lsp. Notice that in the first print batch we have the AST for the command `Section theorems.`. However, the corresponding range has the same line and characters for its start and end positions, even though the offset seems to be right as `len("Section theorems.") == 10872 - 10855`.

**Expected behavior**
The AST returned by coq-lsp should contain the correct ranges for *all* valid steps. In this specific example, I believe the range of `Section theorems.` should be:
```python
Range: {'start': "{'line': 276, 'character': 0, 'offset': 10855}", 'end': "{'line': 276, 'character': 17, 'offset': 10872}"}
```

**Desktop:**
 - Operating system: EndeavourOS (also witnessed in other Linux distributions)
 - coq-lsp version: 0.1.8
 - Coq version: 8.18.0

**Comment by Alizter** [comment]
I think I've experienced this bug in practice, and I suspect it is to do with how we memoize the step. When we have an error, we report the location, but since we drop locations in comparison, the location is never updated as the document progresses leading to stale locations.

**Comment by ejgallego** [comment]
Indeed I think @Alizter is on the right track here, the current code we have may still have some corner cases.

Having a simpler way to reproduce would help, as I'm quite short on cycles these days.

See also #201 , I wouldn't be suprised if this a duplicate.

**Comment by pcarrott** [comment]
This should make the example easier to reproduce. No need to download the file and you should be able to run it in any Coq 8.18 environment.
```
```

**Comment by ejgallego** [comment]
I understood the problem finally, it was indeed just a wrong error recovery on the lexer side.

Coq PR: https://github.com/coq/coq/pull/18893

Folks, you need to backport that path to the Coq version you are using (or use coq-lsp `main`  branch).
