### ISSUE TITLE
Errors: Restart cannot be used through the Load command;

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#827]
Wasn't this supported before?

```coq
Goal nat -> nat.
intro x.
Restart.
```

```
Errors:
Restart cannot be used through the Load command;
```

**Comment by ejgallego** [comment]
Hi @Alizter , oh, indeed `Restart` is not supported, see comment in `coq/ast.ml` and `examples/metaCommands.v`.

Adding support to it is trivial tho, I just was lazy I guess (restart is much less interesting that reset)

**Comment by Alizter** [comment]
`Undo` also gives the same error.

**Comment by Alizter** [comment]
@ejgallego I don't need them but occasionally people share snippets of Coq code including those commands. I thought that there was support for this in coq-lsp but maybe I remembered wrong. In any case, if it was not intended to be supported then that is fine.

**Comment by SkySkimmer** [comment]
Proof general uses BackTo AFAICT

**Comment by ejgallego** [comment]
IMHO the mess we have with `Undo` / `Back` / `BackTo` could be first removed upstream, IMHO it only makes sense to have one command like this?

More complex applications should interact IMHO with the DM directly.

**Comment by Alizter** [comment]
We've tried to deprecate/remove these commands previously, but there has always been some push back from users who use it interactively with students. Not every command should be used in a proof script, but some are useful for demonstration purposes.

**Comment by ejgallego** [comment]
I am talking about having 3 commands doing conceptually the same thing, IMHO if users want the meta commands, why not. They are useful, cheap to implement, and allow cool hacks as documented in our manual.
