### ISSUE TITLE
Unvierse levels displayed as de bruijin indices in hover

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#835]
When hovering over a term with `Set Printing Universes`, we expect to see nicely named universe variables.
```coq
From Coq Require Import Prelude.
Set Printing Universes.
Set Universe Polymorphism.

Inductive foo : Type := bar : Type -> foo.

Print foo.
```

Here `Print` outputs the following:
```coq
Inductive foo@{u} : Type@{u+1} :=  bar : Type@{u} -> foo@{u}.
(* u |=  *)

Arguments bar _%type_scope
```
Which is reasonable. However hovering over `foo` outputs:
```coq
foo : Type@{Var(0)+1}
```
which is not very readable. Since `About` and `Print` are able to provide reasonable terms, it seems there is some configuration missing in the term printer.

**Comment by Alizter** [comment]
Note that there are perhaps two bugs here:
1. Universe variables should have good names.
2. The universe variables should appear on the LHS like in `Print`.

**Comment by Alizter** [comment]
@ejgallego Any idea why this might be the case and how it can be fixed?

**Comment by ejgallego** [comment]
This is very annoying yes.
