### ISSUE TITLE
Improve error handling for Coq internal errors

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-lsp#91]
If we get an anomaly from Fleche (usually from Coq), the way the server behaves is far from ideal.

We are also not very well protected for exceptions happening in the request code.

**Comment by ejgallego** [comment]
Postponed as I forgot of an example where this bad behavior occurs.

**Comment by Alizter** [comment]
Aren't there known ways to get anomlies just by searching Coq issues?

**Comment by Alizter** [comment]
Also just load a plugin which raises an exception if you want to test.

**Comment by ejgallego** [comment]
Good ideas! Thanks.

**Comment by ejgallego** [comment]
I know have a precise description of the problem:

If we are serving a `didOpen` notification for example, and we get an anomaly in some path that is not handled by Coq protect, sometimes we won't add a document handler for this, then further requests fail.

The correct behavior would be I guess to cancel the request.

@artagnon 's patch to replace `find` by `find_opt` would already help here.
